package com.dilanka456.myprojectcustomer10.Model;
// Generated Mar 12, 2021 9:19:33 AM by Hibernate Tools 4.3.1



/**
 * CustomerOpt generated by hbm2java
 */
public class CustomerOpt  implements java.io.Serializable {


    private int idcustomerOpt;
    private String email;
    private Integer otp;

    public CustomerOpt() {
    }


    public CustomerOpt(int idcustomerOpt) {
        this.idcustomerOpt = idcustomerOpt;
    }
    public CustomerOpt(int idcustomerOpt, String email, Integer otp) {
        this.idcustomerOpt = idcustomerOpt;
        this.email = email;
        this.otp = otp;
    }

    public int getIdcustomerOpt() {
        return this.idcustomerOpt;
    }

    public void setIdcustomerOpt(int idcustomerOpt) {
        this.idcustomerOpt = idcustomerOpt;
    }
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getOtp() {
        return this.otp;
    }

    public void setOtp(Integer otp) {
        this.otp = otp;
    }




}


